### PR TITLE
SftpPoller supports polling from multiple directories

### PR DESCRIPTION
**Pull request by alachata-qore**

### CODE REVIEW

**Comment by davidnich** [comment]
@alachata-qore - problems:
- the build is failing - please fix
- do not include trailing \n characters in log calls
- use %y instead of %n in all log / *printf statements - please revert the opposite changes you made and change the new stmts to use %y
- please use "filepath" for the full file path in the return value to be consistent with the FilePoller module

**Comment by omusil24** [comment]
@davidnich The build is failing now because of the changes you made yesterday with the sleep function and *code. Having both a function and *code member variable the same is a really bad idea.

``````
unhandled QORE System exception thrown in TID 2 at 2016-04-22 10:36:19.329905 Fri +02:00 (CEST) in SftpPoller::run() (/var/lib/jenkins/workspace/module-ssh2/qlib/SftpPoller.qm:722, user code)
REFERENCE-CALL-ERROR: expression does not evaluate to a call reference (evaluated to type 'NOTHING')
call stack:
  1: SftpPoller::run() (/var/lib/jenkins/workspace/module-ssh2/qlib/SftpPoller.qm:591, user code)```
``````

**Comment by davidnich** [comment]
@omusil24 ok thanks now that's fixed in this branch

**Comment by omusil24** [comment]
@davidnich SftpPoller.qtest fell into an endless loop.

**Pull request merged**
