### PR TITLE
refs qorelanguage/qore#2549 fixed a bug reading zero-length files wit…

### PR DESCRIPTION
**Pull request by davidnich**
…h SFTPClient::get*File()

### CODE REVIEW

**Comment by tehe** [comment]
Also, the following two methods seem to suffer from the same problem:
src/SFTPClient.cpp`SFTPClient::sftpGet()
srf/SFTPClient.cpp`SFTPClient::sftpRetrieveFile()

**Comment by davidnich** [comment]
@tehe excellent - good catch - now also those are fixed

**Comment by davidnich** [comment]
@tehe oops, now fixed

**Comment by tehe** [comment]
LGTM. Thanks for fixing this.

**Pull request merged**
